//
//  Copyright 2020 Docker, Inc.

//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at

//      http://www.apache.org/licenses/LICENSE-2.0

//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.2
// source: protos/compose/v1/compose.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ComposeServiceUpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectName string   `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	WorkDir     string   `protobuf:"bytes,2,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Files       []string `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *ComposeServiceUpRequest) Reset() {
	*x = ComposeServiceUpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_compose_v1_compose_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposeServiceUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeServiceUpRequest) ProtoMessage() {}

func (x *ComposeServiceUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_compose_v1_compose_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeServiceUpRequest.ProtoReflect.Descriptor instead.
func (*ComposeServiceUpRequest) Descriptor() ([]byte, []int) {
	return file_protos_compose_v1_compose_proto_rawDescGZIP(), []int{0}
}

func (x *ComposeServiceUpRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ComposeServiceUpRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *ComposeServiceUpRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type ComposeServiceUpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ComposeServiceUpResponse) Reset() {
	*x = ComposeServiceUpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_compose_v1_compose_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposeServiceUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeServiceUpResponse) ProtoMessage() {}

func (x *ComposeServiceUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_compose_v1_compose_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeServiceUpResponse.ProtoReflect.Descriptor instead.
func (*ComposeServiceUpResponse) Descriptor() ([]byte, []int) {
	return file_protos_compose_v1_compose_proto_rawDescGZIP(), []int{1}
}

type ComposeServiceDownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ComposeServiceDownRequest) Reset() {
	*x = ComposeServiceDownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_compose_v1_compose_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposeServiceDownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeServiceDownRequest) ProtoMessage() {}

func (x *ComposeServiceDownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_compose_v1_compose_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeServiceDownRequest.ProtoReflect.Descriptor instead.
func (*ComposeServiceDownRequest) Descriptor() ([]byte, []int) {
	return file_protos_compose_v1_compose_proto_rawDescGZIP(), []int{2}
}

type ComposeServiceDownResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ComposeServiceDownResponse) Reset() {
	*x = ComposeServiceDownResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_compose_v1_compose_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposeServiceDownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeServiceDownResponse) ProtoMessage() {}

func (x *ComposeServiceDownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_compose_v1_compose_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeServiceDownResponse.ProtoReflect.Descriptor instead.
func (*ComposeServiceDownResponse) Descriptor() ([]byte, []int) {
	return file_protos_compose_v1_compose_proto_rawDescGZIP(), []int{3}
}

var File_protos_compose_v1_compose_proto protoreflect.FileDescriptor

var file_protos_compose_v1_compose_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x20, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65,
	0x2e, 0x76, 0x31, 0x22, 0x6d, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b,
	0x0a, 0x19, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x6f, 0x77,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x91, 0x02, 0x0a, 0x0e, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7b, 0x0a, 0x02,
	0x55, 0x70, 0x12, 0x39, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x81, 0x01, 0x0a, 0x04, 0x44, 0x6f,
	0x77, 0x6e, 0x12, 0x3b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x3c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a,
	0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_compose_v1_compose_proto_rawDescOnce sync.Once
	file_protos_compose_v1_compose_proto_rawDescData = file_protos_compose_v1_compose_proto_rawDesc
)

func file_protos_compose_v1_compose_proto_rawDescGZIP() []byte {
	file_protos_compose_v1_compose_proto_rawDescOnce.Do(func() {
		file_protos_compose_v1_compose_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_compose_v1_compose_proto_rawDescData)
	})
	return file_protos_compose_v1_compose_proto_rawDescData
}

var file_protos_compose_v1_compose_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_compose_v1_compose_proto_goTypes = []interface{}{
	(*ComposeServiceUpRequest)(nil),    // 0: com.docker.api.protos.compose.v1.ComposeServiceUpRequest
	(*ComposeServiceUpResponse)(nil),   // 1: com.docker.api.protos.compose.v1.ComposeServiceUpResponse
	(*ComposeServiceDownRequest)(nil),  // 2: com.docker.api.protos.compose.v1.ComposeServiceDownRequest
	(*ComposeServiceDownResponse)(nil), // 3: com.docker.api.protos.compose.v1.ComposeServiceDownResponse
}
var file_protos_compose_v1_compose_proto_depIdxs = []int32{
	0, // 0: com.docker.api.protos.compose.v1.ComposeService.Up:input_type -> com.docker.api.protos.compose.v1.ComposeServiceUpRequest
	2, // 1: com.docker.api.protos.compose.v1.ComposeService.Down:input_type -> com.docker.api.protos.compose.v1.ComposeServiceDownRequest
	1, // 2: com.docker.api.protos.compose.v1.ComposeService.Up:output_type -> com.docker.api.protos.compose.v1.ComposeServiceUpResponse
	3, // 3: com.docker.api.protos.compose.v1.ComposeService.Down:output_type -> com.docker.api.protos.compose.v1.ComposeServiceDownResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_compose_v1_compose_proto_init() }
func file_protos_compose_v1_compose_proto_init() {
	if File_protos_compose_v1_compose_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_compose_v1_compose_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComposeServiceUpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_compose_v1_compose_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComposeServiceUpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_compose_v1_compose_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComposeServiceDownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_compose_v1_compose_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComposeServiceDownResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_compose_v1_compose_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_compose_v1_compose_proto_goTypes,
		DependencyIndexes: file_protos_compose_v1_compose_proto_depIdxs,
		MessageInfos:      file_protos_compose_v1_compose_proto_msgTypes,
	}.Build()
	File_protos_compose_v1_compose_proto = out.File
	file_protos_compose_v1_compose_proto_rawDesc = nil
	file_protos_compose_v1_compose_proto_goTypes = nil
	file_protos_compose_v1_compose_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ComposeServiceClient is the client API for ComposeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ComposeServiceClient interface {
	Up(ctx context.Context, in *ComposeServiceUpRequest, opts ...grpc.CallOption) (*ComposeServiceUpResponse, error)
	Down(ctx context.Context, in *ComposeServiceDownRequest, opts ...grpc.CallOption) (*ComposeServiceDownResponse, error)
}

type composeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComposeServiceClient(cc grpc.ClientConnInterface) ComposeServiceClient {
	return &composeServiceClient{cc}
}

func (c *composeServiceClient) Up(ctx context.Context, in *ComposeServiceUpRequest, opts ...grpc.CallOption) (*ComposeServiceUpResponse, error) {
	out := new(ComposeServiceUpResponse)
	err := c.cc.Invoke(ctx, "/com.docker.api.protos.compose.v1.ComposeService/Up", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *composeServiceClient) Down(ctx context.Context, in *ComposeServiceDownRequest, opts ...grpc.CallOption) (*ComposeServiceDownResponse, error) {
	out := new(ComposeServiceDownResponse)
	err := c.cc.Invoke(ctx, "/com.docker.api.protos.compose.v1.ComposeService/Down", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComposeServiceServer is the server API for ComposeService service.
type ComposeServiceServer interface {
	Up(context.Context, *ComposeServiceUpRequest) (*ComposeServiceUpResponse, error)
	Down(context.Context, *ComposeServiceDownRequest) (*ComposeServiceDownResponse, error)
}

// UnimplementedComposeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedComposeServiceServer struct {
}

func (*UnimplementedComposeServiceServer) Up(context.Context, *ComposeServiceUpRequest) (*ComposeServiceUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Up not implemented")
}
func (*UnimplementedComposeServiceServer) Down(context.Context, *ComposeServiceDownRequest) (*ComposeServiceDownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Down not implemented")
}

func RegisterComposeServiceServer(s *grpc.Server, srv ComposeServiceServer) {
	s.RegisterService(&_ComposeService_serviceDesc, srv)
}

func _ComposeService_Up_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComposeServiceUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposeServiceServer).Up(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.docker.api.protos.compose.v1.ComposeService/Up",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposeServiceServer).Up(ctx, req.(*ComposeServiceUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComposeService_Down_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComposeServiceDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposeServiceServer).Down(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.docker.api.protos.compose.v1.ComposeService/Down",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposeServiceServer).Down(ctx, req.(*ComposeServiceDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ComposeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.docker.api.protos.compose.v1.ComposeService",
	HandlerType: (*ComposeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Up",
			Handler:    _ComposeService_Up_Handler,
		},
		{
			MethodName: "Down",
			Handler:    _ComposeService_Down_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/compose/v1/compose.proto",
}
