run:
  build-tags:
    - kube
    - e2e
  timeout: 10m
  concurrency: 2
  skip-dirs:
    - tests/composefiles 
linters:
  enable-all: false
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
linters-settings:
  gocyclo:
    min-complexity: 16
  lll:
    line-length: 200
issues:
  # golangci hides some golint warnings (the warning about exported things
  # withtout documentation for example), this will make it show them anyway.
  exclude-use-default: false
  exclude:
    - should not use dot imports
