/*
   Copyright 2022 Docker Compose CLI authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package metrics

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"net/url"
)

type AnalyticsRequest struct {
	Event string      `json:"event"`
	Body  interface{} `json:"body"`
}

// Reporter reports metric events generated by the client.
type Reporter interface {
	// Heartbeat reports a metric for aggregation.
	Heartbeat(cmd CommandUsage)

	// Event reports an analytics action.
	Event(cmd DockerCLIEvent)
}

// HTTPReporter reports metric events to an HTTP endpoint.
type HTTPReporter struct {
	client *http.Client
}

// NewHTTPReporter creates a new reporter that will report metric events using
// the provided HTTP client.
func NewHTTPReporter(client *http.Client) HTTPReporter {
	return HTTPReporter{client: client}
}

// Heartbeat reports a metric for aggregation.
func (l HTTPReporter) Heartbeat(cmd CommandUsage) {
	l.post("/usage", cmd)
}

// Event reports an analytics action.
func (l HTTPReporter) Event(cmd DockerCLIEvent) {
	event := AnalyticsRequest{
		Event: "eventCliCommand",
		Body:  cmd,
	}
	l.post("/analytics/track", event)
}

func (l HTTPReporter) post(path string, body interface{}) {
	entry, err := json.Marshal(body)
	if err != nil {
		// we only pass known types that will marshal without error (no cycles)
		return
	}

	u, err := url.JoinPath("http://ipc", path)
	if err != nil {
		// we only pass known values here, so this isn't possible in practice
		return
	}

	resp, _ := l.client.Post(u, "application/json", bytes.NewReader(entry))
	if resp != nil && resp.Body != nil {
		_ = resp.Body.Close()
	}
}

// WriterReporter reports metrics as JSON lines to the provided writer.
type WriterReporter struct {
	w io.Writer
}

// NewWriterReporter creates a new reporter that will write metrics to the
// provided writer as JSON lines.
func NewWriterReporter(w io.Writer) WriterReporter {
	return WriterReporter{w: w}
}

// Heartbeat reports a metric for aggregation.
func (w WriterReporter) Heartbeat(cmd CommandUsage) {
	w.write(cmd)
}

// Event reports an analytics action.
func (w WriterReporter) Event(cmd DockerCLIEvent) {
	w.write(cmd)
}

func (w WriterReporter) write(v interface{}) {
	entry, err := json.Marshal(v)
	if err != nil {
		// we only pass known types that will marshal without error (no cycles)
		return
	}
	entry = append(entry, '\n')
	_, _ = w.w.Write(entry)
}

// MuxReporter wraps multiple reporter instances and reports metrics to each
// instance on invocation.
type MuxReporter struct {
	reporters []Reporter
}

// NewMuxReporter creates a reporter that will report metrics to each of the
// provided reporter instances.
func NewMuxReporter(reporters ...Reporter) MuxReporter {
	return MuxReporter{reporters: reporters}
}

// Heartbeat reports a metric for aggregation.
func (m MuxReporter) Heartbeat(cmd CommandUsage) {
	for i := range m.reporters {
		m.reporters[i].Heartbeat(cmd)
	}
}

// Event reports an analytics action.
func (m MuxReporter) Event(cmd DockerCLIEvent) {
	for i := range m.reporters {
		m.reporters[i].Event(cmd)
	}
}
