name: Continuous integration

on:
  issue_comment:
    types: [created, edited]
  pull_request:

jobs:
  build:
    name: ACI e2e tests
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: runacitest
        with:
          trigger: '@test-aci'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Set up Go 1.14
        if: steps.runacitest.outputs.triggered == 'true'
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Checkout code into the Go module directory
        if: steps.runacitest.outputs.triggered == 'true'
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        if: steps.runacitest.outputs.triggered == 'true'
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}

      - name: Build for ACI e2e tests
        if: steps.runacitest.outputs.triggered == 'true'
        run: make -f builder.Makefile cli

      - name: ACI e2e Test
        if: steps.runacitest.outputs.triggered == 'true'
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: make e2e-aci

  windows-build:
    name: Windows Build
    runs-on: windows-latest
    env:
      GO111MODULE: "on"
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: runwindowstests
        with:
          trigger: '@test-windows'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Set up Go 1.14
        if: steps.runwindowstests.outputs.triggered == 'true'
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Checkout code into the Go module directory
        if: steps.runwindowstests.outputs.triggered == 'true'
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        if: steps.runwindowstests.outputs.triggered == 'true'
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}

      - name: Test
        if: steps.runwindowstests.outputs.triggered == 'true'
        env:
          BUILD_TAGS: example,local
        run: make -f builder.Makefile test

      - name: Build
        if: steps.runwindowstests.outputs.triggered == 'true'
        env:
          BUILD_TAGS: example,local
        run: make -f builder.Makefile cli

      - name: E2E Test
        if: steps.runwindowstests.outputs.triggered == 'true'
        run: make e2e-win-ci

      - name: ACI e2e Test
        if: steps.runwindowstests.outputs.triggered == 'true'
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: make e2e-aci
